name: AWS EC2 Instance Setup and Connect to RDS

on:
  push:
    branches:
      - main  # You can change this to the branch you want the workflow to run on

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # aws-region: us-east-1  # Change to your region
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1  # Change to your region

    - name: Launch EC2 instance
      run: |
        # Define EC2 instance parameters
        INSTANCE_TYPE="t2.micro"  # Change as needed
        KEY_NAME="awst7545-mumbai"  # Change to your key pair name
        SECURITY_GROUP="sg-014d30ace7995febb"  # Change to your security group
        AMI_ID="ami-00bb6a80f01f03502"  # Example Ubuntu AMI, change if needed
        SUBNET_ID="subnet-0f2c630e7eee03e9f"  # Change to your subnet ID

    - name: Launch EC2 instance
      id: launch-instance
      run: |
        INSTANCE_ID=$(aws ec2 run-instances \
          --image-id $AMI_ID \
          --instance-type $INSTANCE_TYPE \
          --key-name $KEY_NAME \
          --security-group-ids $SECURITY_GROUP \
          --subnet-id $SUBNET_ID \
          --query 'Instances[0].InstanceId' \
          --output text)
      echo "Launched EC2 instance with ID: $INSTANCE_ID"
      echo "::set-output name=instance_id::$INSTANCE_ID"

# - name: Wait for EC2 instance to be running
#   run: |
#     INSTANCE_STATE=$(aws ec2 describe-instances \
#       --instance-ids ${{ steps.launch-instance.outputs.instance_id }} \
#       --query 'Reservations[0].Instances[0].State.Name' \
#       --output text)

#     while [[ "$INSTANCE_STATE" != "running" ]]; do
#       echo "Waiting for EC2 instance to be running..."
#       sleep 30  # Sleep time before checking again
#       INSTANCE_STATE=$(aws ec2 describe-instances \
#         --instance-ids ${{ steps.launch-instance.outputs.instance_id }} \
#         --query 'Reservations[0].Instances[0].State.Name' \
#         --output text)
#     done

#     echo "EC2 instance is running."

# - name: Debug EC2 Instance Details
#   run: |
#     aws ec2 describe-instances --instance-ids ${{ steps.launch-instance.outputs.instance_id }} \
#       --query 'Reservations[0].Instances[0].[InstanceId, PublicIpAddress, State.Name]' \
#       --output table

# - name: Wait for EC2 instance to have a public IP
#   run: |
#     echo "Sleeping to allow public IP assignment..."
#     sleep 60  # Extra sleep to allow public IP assignment
#     EC2_PUBLIC_IP=$(aws ec2 describe-instances \
#       --instance-ids ${{ steps.launch-instance.outputs.instance_id }} \
#       --query 'Reservations[0].Instances[0].PublicIpAddress' \
#       --output text)

#     echo "EC2 Public IP: $EC2_PUBLIC_IP"
#     echo "::set-output name=public_ip::$EC2_PUBLIC_IP"
